; Common configuration for all Teensy 4.1 boards
[env]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
    zischknall/BohleBots_BNO055
    Wire

; Environment for the standard 'main.cpp'
[env:base_unit]
src_filter = +<*> -<camera-main.cpp> -<line-main.cpp>

; Environment for the camera controller
[env:camera_unit]
src_filter = +<*> -<main.cpp> -<line-main.cpp>
build_src_filter = +<camera-main.cpp>

; Environment for the line follower/sensor unit
[env:line_unit]
src_filter = +<*> -<main.cpp> -<camera-main.cpp>
build_src_filter = +<line-main.cpp>