; Common configuration for all Teensy boards
[env]
platform = teensy
framework = arduino
lib_deps = 
    zischknall/BohleBots_BNO055
    Wire

; Environment for the standard 'main.cpp'
[env:base_unit]
board = teensy40
build_src_filter = +<camera-main.cpp>
lib_extra_dirs = lib

; Environment for the camera controller
[env:camera_unit]
board = teensy40
build_src_filter = +<camera-main.cpp>
lib_extra_dirs = lib

; Environment for the line follower/sensor unit
[env:line_unit]
board = teensy41
build_src_filter = +<line-main.cpp>
lib_deps = 
    adafruit/Adafruit NeoPixel
lib_extra_dirs = lib